name: Update README

on:
  schedule:
    - cron: "0 */12 * * *" # se ejecuta cada 12 horas
  workflow_dispatch: # puedes ejecutarlo manualmente desde la pestaña Actions

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          token: ${{ secrets.PAT_1 }}
